version: '3'

services:

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8181:80
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/java6/uploads:/uploads
    depends_on:
      - db

volumes:
  dbdata: